#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gpsd
Version  : 3.25
Release  : 5
URL      : https://download-mirror.savannah.gnu.org/releases/gpsd/gpsd-3.25.tar.xz
Source0  : https://download-mirror.savannah.gnu.org/releases/gpsd/gpsd-3.25.tar.xz
Summary  : Service daemon for mediating access to a GPS
Group    : Development/Tools
License  : BSD-2-Clause
Requires: gpsd-bin = %{version}-%{release}
Requires: gpsd-config = %{version}-%{release}
Requires: gpsd-data = %{version}-%{release}
Requires: gpsd-lib = %{version}-%{release}
Requires: gpsd-license = %{version}-%{release}
Requires: gpsd-man = %{version}-%{release}
Requires: gpsd-python = %{version}-%{release}
Requires: gpsd-python3 = %{version}-%{release}
Requires: gpsd-services = %{version}-%{release}
BuildRequires : bind-utils-dev
BuildRequires : buildreq-scons
BuildRequires : glibc-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(bluez)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(py3cairo)
BuildRequires : pkgconfig(pygobject-3.0)
BuildRequires : pypi-pyserial
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Install-python-packages-in-expected-dir.patch
Patch2: 0002-Don-t-attempt-daemon-reload-during-build.patch

%description
gpsd is a service daemon that mediates access to a GPS sensor
connected to the host computer by serial or USB interface, making its
data on the location/course/velocity of the sensor available to be
queried on TCP port 2947 of the host computer.  With gpsd, multiple
GPS client applications (such as navigational and wardriving software)
can share access to a GPS without contention or loss of data.  Also,
gpsd responds to queries with a format that is substantially easier to
parse than NMEA 0183.

%package bin
Summary: bin components for the gpsd package.
Group: Binaries
Requires: gpsd-data = %{version}-%{release}
Requires: gpsd-config = %{version}-%{release}
Requires: gpsd-license = %{version}-%{release}
Requires: gpsd-services = %{version}-%{release}

%description bin
bin components for the gpsd package.


%package config
Summary: config components for the gpsd package.
Group: Default

%description config
config components for the gpsd package.


%package data
Summary: data components for the gpsd package.
Group: Data

%description data
data components for the gpsd package.


%package dev
Summary: dev components for the gpsd package.
Group: Development
Requires: gpsd-lib = %{version}-%{release}
Requires: gpsd-bin = %{version}-%{release}
Requires: gpsd-data = %{version}-%{release}
Provides: gpsd-devel = %{version}-%{release}
Requires: gpsd = %{version}-%{release}

%description dev
dev components for the gpsd package.


%package lib
Summary: lib components for the gpsd package.
Group: Libraries
Requires: gpsd-data = %{version}-%{release}
Requires: gpsd-license = %{version}-%{release}

%description lib
lib components for the gpsd package.


%package license
Summary: license components for the gpsd package.
Group: Default

%description license
license components for the gpsd package.


%package man
Summary: man components for the gpsd package.
Group: Default

%description man
man components for the gpsd package.


%package python
Summary: python components for the gpsd package.
Group: Default
Requires: gpsd-python3 = %{version}-%{release}

%description python
python components for the gpsd package.


%package python3
Summary: python3 components for the gpsd package.
Group: Default
Requires: python3-core

%description python3
python3 components for the gpsd package.


%package services
Summary: services components for the gpsd package.
Group: Systemd services

%description services
services components for the gpsd package.


%prep
%setup -q -n gpsd-3.25
cd %{_builddir}/gpsd-3.25
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
scons prefix=/usr \
sbindir=bin \
libdir=/usr/lib64 \
udevdir=%{buildroot}/usr/lib/udev \
unitdir=/usr/lib/systemd/system \
qt_versioned=5

%install
scons install --install-sandbox=%{buildroot} \
udev-install
mkdir -p %{buildroot}/usr/share/package-licenses/gpsd
cp %{_builddir}/gpsd-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gpsd/b58fbf3e442f75b7b3fb8588b8ff94d2c00620a9 || :
cp %{_builddir}/gpsd-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/gpsd/34c5034377edef1080538bd0d4f5cf9b78e22dff || :

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cgps
/usr/bin/gegps
/usr/bin/gps2udp
/usr/bin/gpscat
/usr/bin/gpscsv
/usr/bin/gpsctl
/usr/bin/gpsd
/usr/bin/gpsdctl
/usr/bin/gpsdebuginfo
/usr/bin/gpsdecode
/usr/bin/gpsfake
/usr/bin/gpsmon
/usr/bin/gpspipe
/usr/bin/gpsplot
/usr/bin/gpsprof
/usr/bin/gpsrinex
/usr/bin/gpssnmp
/usr/bin/gpssubframe
/usr/bin/gpxlogger
/usr/bin/lcdgps
/usr/bin/ntpshmmon
/usr/bin/ppscheck
/usr/bin/ubxtool
/usr/bin/xgps
/usr/bin/xgpsspeed
/usr/bin/zerk

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/25-gpsd.rules

%files data
%defattr(-,root,root,-)
/usr/share/gpsd/doc/AUTHORS
/usr/share/gpsd/doc/COPYING
/usr/share/gpsd/doc/NEWS
/usr/share/gpsd/doc/README.adoc
/usr/share/gpsd/doc/SUPPORT.adoc
/usr/share/gpsd/doc/build.adoc
/usr/share/gpsd/doc/example1.c.txt
/usr/share/gpsd/doc/example2.py.txt
/usr/share/gpsd/icons/gpsd-logo.png
/usr/share/snmp/mibs/gpsd/GPSD-MIB

%files dev
%defattr(-,root,root,-)
/usr/include/gps.h
/usr/include/libgpsmm.h
/usr/lib64/libQgpsmm.prl
/usr/lib64/libQgpsmm.so
/usr/lib64/libgps.so
/usr/lib64/libgpsdpacket.so
/usr/lib64/pkgconfig/Qgpsmm.pc
/usr/lib64/pkgconfig/libgps.pc
/usr/share/man/man3/libQgpsmm.3
/usr/share/man/man3/libgps.3
/usr/share/man/man3/libgpsmm.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQgpsmm.so.30
/usr/lib64/libQgpsmm.so.30.0.0
/usr/lib64/libgps.so.30
/usr/lib64/libgps.so.30.0.0
/usr/lib64/libgpsdpacket.so.30
/usr/lib64/libgpsdpacket.so.30.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gpsd/34c5034377edef1080538bd0d4f5cf9b78e22dff
/usr/share/package-licenses/gpsd/b58fbf3e442f75b7b3fb8588b8ff94d2c00620a9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cgps.1
/usr/share/man/man1/gegps.1
/usr/share/man/man1/gps.1
/usr/share/man/man1/gps2udp.1
/usr/share/man/man1/gpscat.1
/usr/share/man/man1/gpscsv.1
/usr/share/man/man1/gpsctl.1
/usr/share/man/man1/gpsdebuginfo.1
/usr/share/man/man1/gpsdecode.1
/usr/share/man/man1/gpsfake.1
/usr/share/man/man1/gpsmon.1
/usr/share/man/man1/gpspipe.1
/usr/share/man/man1/gpsplot.1
/usr/share/man/man1/gpsprof.1
/usr/share/man/man1/gpsrinex.1
/usr/share/man/man1/gpssnmp.1
/usr/share/man/man1/gpssubframe.1
/usr/share/man/man1/gpxlogger.1
/usr/share/man/man1/lcdgps.1
/usr/share/man/man1/ntpshmmon.1
/usr/share/man/man1/ubxtool.1
/usr/share/man/man1/xgps.1
/usr/share/man/man1/xgpsspeed.1
/usr/share/man/man1/zerk.1
/usr/share/man/man5/gpsd_json.5
/usr/share/man/man8/gpsd.8
/usr/share/man/man8/gpsdctl.8
/usr/share/man/man8/gpsinit.8
/usr/share/man/man8/ppscheck.8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/gpsd.service
/usr/lib/systemd/system/gpsd.socket
/usr/lib/systemd/system/gpsdctl@.service
